import pg from 'pg';

const { Client } = pg;

const DB_CONNECTION = String(process.env.DATABASE_URL || '').trim();
if (!DB_CONNECTION) {
  throw new Error('Missing DATABASE_URL in environment variables.');
}

const client = new Client({ connectionString: DB_CONNECTION });

async function migrate() {
  await client.connect();

  await client.query(`
    CREATE TABLE IF NOT EXISTS contacts (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT '',
      company TEXT NOT NULL DEFAULT '',
      category TEXT NOT NULL DEFAULT 'General',
      email TEXT NOT NULL DEFAULT '',
      phone TEXT NOT NULL DEFAULT '',
      notes TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await client.query(`ALTER TABLE contacts ENABLE ROW LEVEL SECURITY`).catch(() => {});
  await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='contacts' AND policyname='Public full access') THEN CREATE POLICY "Public full access" ON contacts FOR ALL USING (true) WITH CHECK (true); END IF; END $$`).catch(() => {});

  console.log('contacts table migration complete');
  await client.end();
}

migrate().catch(async (err) => {
  console.error('contacts migration failed:', err?.message || err);
  try {
    await client.end();
  } catch {}
  process.exit(1);
});
