#!/usr/bin/env node

import pg from 'pg';
const { Client } = pg;

async function migrate() {
  const client = new Client({
    connectionString: 'postgresql://postgres:211919448a449a8c985b520fc3895aeb@arqsta8h.us-west.database.insforge.app:5432/insforge?sslmode=require'
  });

  try {
    console.log('Connecting to database...');
    await client.connect();
    console.log('✓ Connected to database');

    console.log('Starting migration: Adding shopping_list_items and cost_calculator_overrides tables...');

    // Create shopping_list_items table
    const createShoppingList = `
      CREATE TABLE IF NOT EXISTS shopping_list_items (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        quantity NUMERIC NOT NULL,
        unit TEXT NOT NULL,
        "totalCost" NUMERIC NOT NULL,
        items TEXT DEFAULT '[]',
        category TEXT NOT NULL,
        department TEXT NOT NULL,
        "purchaseType" TEXT,
        "vendorName" TEXT,
        "storeName" TEXT,
        "storeUrl" TEXT,
        "sourceKey" TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;

    const alterShoppingList = `
      ALTER TABLE shopping_list_items ADD COLUMN IF NOT EXISTS "purchaseType" TEXT;
      ALTER TABLE shopping_list_items ADD COLUMN IF NOT EXISTS "vendorName" TEXT;
      ALTER TABLE shopping_list_items ADD COLUMN IF NOT EXISTS "storeName" TEXT;
      ALTER TABLE shopping_list_items ADD COLUMN IF NOT EXISTS "storeUrl" TEXT;
    `;

    // Create cost_calculator_overrides table
    const createCostCalcOverrides = `
      CREATE TABLE IF NOT EXISTS cost_calculator_overrides (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "itemId" BIGINT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
        price NUMERIC NOT NULL,
        "targetFoodCost" NUMERIC NOT NULL,
        ingredients JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;

    // Enable RLS
    const enableRLS1 = `
      ALTER TABLE shopping_list_items ENABLE ROW LEVEL SECURITY;
      CREATE POLICY IF NOT EXISTS "Public full access" ON shopping_list_items FOR ALL USING (true) WITH CHECK (true);
    `;

    const enableRLS2 = `
      ALTER TABLE cost_calculator_overrides ENABLE ROW LEVEL SECURITY;
      CREATE POLICY IF NOT EXISTS "Public full access" ON cost_calculator_overrides FOR ALL USING (true) WITH CHECK (true);
    `;

    // Execute migrations
    await client.query(createShoppingList);
    console.log('✓ Created shopping_list_items table');

    await client.query(alterShoppingList);
    console.log('✓ Ensured shopping_list_items purchase-source columns exist');

    await client.query(createCostCalcOverrides);
    console.log('✓ Created cost_calculator_overrides table');

    try {
      await client.query(enableRLS1);
      console.log('✓ Enabled RLS on shopping_list_items');
    } catch (e) {
      console.warn('Warning: Could not enable RLS on shopping_list_items (may already be enabled)');
    }

    try {
      await client.query(enableRLS2);
      console.log('✓ Enabled RLS on cost_calculator_overrides');
    } catch (e) {
      console.warn('Warning: Could not enable RLS on cost_calculator_overrides (may already be enabled)');
    }

    console.log('✅ Migration complete!');
  } catch (e) {
    console.error('❌ Migration failed:', e.message);
    process.exit(1);
  } finally {
    await client.end();
  }
}

migrate();

