#!/usr/bin/env node
import { insforge } from './src/services/insforge.ts';

async function migrate() {
  try {
    console.log('Starting migration: Adding shopping_list_items and cost_calculator_overrides tables...');
    
    // Create shopping_list_items table
    const createShoppingList = `
      CREATE TABLE IF NOT EXISTS shopping_list_items (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL,
        quantity NUMERIC NOT NULL,
        unit TEXT NOT NULL,
        "totalCost" NUMERIC NOT NULL,
        items TEXT DEFAULT '[]',
        category TEXT NOT NULL,
        department TEXT NOT NULL,
        "sourceKey" TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;

    // Create cost_calculator_overrides table
    const createCostCalcOverrides = `
      CREATE TABLE IF NOT EXISTS cost_calculator_overrides (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "itemId" BIGINT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
        price NUMERIC NOT NULL,
        "targetFoodCost" NUMERIC NOT NULL,
        ingredients JSONB DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `;

    // Enable RLS
    const enableRLS1 = `
      ALTER TABLE shopping_list_items ENABLE ROW LEVEL SECURITY;
      CREATE POLICY IF NOT EXISTS "Public full access" ON shopping_list_items FOR ALL USING (true) WITH CHECK (true);
    `;

    const enableRLS2 = `
      ALTER TABLE cost_calculator_overrides ENABLE ROW LEVEL SECURITY;
      CREATE POLICY IF NOT EXISTS "Public full access" ON cost_calculator_overrides FOR ALL USING (true) WITH CHECK (true);
    `;

    // Execute migrations using raw SQL via Insforge SDK
    const { error: err1 } = await insforge.sql.execute(createShoppingList);
    if (err1) throw new Error(`Failed to create shopping_list_items: ${err1}`);
    console.log('✓ Created shopping_list_items table');

    const { error: err2 } = await insforge.sql.execute(createCostCalcOverrides);
    if (err2) throw new Error(`Failed to create cost_calculator_overrides: ${err2}`);
    console.log('✓ Created cost_calculator_overrides table');

    const { error: err3 } = await insforge.sql.execute(enableRLS1);
    if (err3) console.warn('Warning: Could not enable RLS on shopping_list_items (may already be enabled)');
    else console.log('✓ Enabled RLS on shopping_list_items');

    const { error: err4 } = await insforge.sql.execute(enableRLS2);
    if (err4) console.warn('Warning: Could not enable RLS on cost_calculator_overrides (may already be enabled)');
    else console.log('✓ Enabled RLS on cost_calculator_overrides');

    console.log('✅ Migration complete!');
  } catch (e) {
    console.error('❌ Migration failed:', e);
    process.exit(1);
  }
}

migrate();
