import pg from 'pg';

const { Client } = pg;

const DB_CONNECTION = String(process.env.DATABASE_URL || '').trim();
if (!DB_CONNECTION) {
  throw new Error('Missing DATABASE_URL in environment variables.');
}

const client = new Client({ connectionString: DB_CONNECTION });

async function migrate() {
  await client.connect();

  await client.query(`
    CREATE TABLE IF NOT EXISTS decision_logs (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      title TEXT NOT NULL,
      decision TEXT NOT NULL DEFAULT '',
      owner TEXT NOT NULL DEFAULT '',
      date TEXT NOT NULL DEFAULT '',
      impact TEXT NOT NULL DEFAULT 'Medium',
      status TEXT NOT NULL DEFAULT 'Proposed',
      "nextStep" TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await client.query(`ALTER TABLE decision_logs ENABLE ROW LEVEL SECURITY`).catch(() => {});
  await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='decision_logs' AND policyname='Public full access') THEN CREATE POLICY "Public full access" ON decision_logs FOR ALL USING (true) WITH CHECK (true); END IF; END $$`).catch(() => {});

  console.log('decision_logs table migration complete');
  await client.end();
}

migrate().catch(async (err) => {
  console.error('decision_logs migration failed:', err?.message || err);
  try {
    await client.end();
  } catch {}
  process.exit(1);
});
