// Creates the ai_messages (AI copilot history) and active_status (partner
// presence) tables. Run with: DATABASE_URL=... node migrate_enhancements.mjs
// The app degrades gracefully when these tables don't exist yet.
import pg from 'pg';

const { Client } = pg;

const DB_CONNECTION = String(process.env.DATABASE_URL || '').trim();
if (!DB_CONNECTION) {
  throw new Error('Missing DATABASE_URL in environment variables.');
}

const client = new Client({ connectionString: DB_CONNECTION });

async function migrate() {
  await client.connect();

  await client.query(`
    CREATE TABLE IF NOT EXISTS ai_messages (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id TEXT NOT NULL DEFAULT '',
      role TEXT NOT NULL DEFAULT 'user',
      content TEXT NOT NULL,
      context TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await client.query(`
    CREATE TABLE IF NOT EXISTS active_status (
      partner_id TEXT PRIMARY KEY,
      current_view TEXT NOT NULL DEFAULT '',
      last_interaction TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  for (const table of ['ai_messages', 'active_status']) {
    await client.query(`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY`).catch(() => {});
    await client.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='${table}' AND policyname='Public full access') THEN CREATE POLICY "Public full access" ON ${table} FOR ALL USING (true) WITH CHECK (true); END IF; END $$`).catch(() => {});
  }

  console.log('enhancements migration complete (ai_messages, active_status)');
  await client.end();
}

migrate().catch(async (err) => {
  console.error('enhancements migration failed:', err?.message || err);
  try {
    await client.end();
  } catch {}
  process.exit(1);
});
