-- SQL SCHEMA FOR NEW RESTAURANT
-- Run this script in the InsForge SQL Editor!

DROP TABLE IF EXISTS tasks, menu_items, startup_costs, operating_costs, milestones, notes, vendors, inventory_items, utility_accounts, permits, marketing_posts, training_modules, daily_checklists, invoices, positions, candidates, activity_logs, digital_assets, shopping_list_items, cost_calculator_overrides CASCADE;

-- 1. Tasks
CREATE TABLE tasks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  task TEXT NOT NULL,
  due TEXT NOT NULL,
  status TEXT NOT NULL,
  priority TEXT NOT NULL,
  checklist JSONB DEFAULT '[]'::jsonb,
  "assignedTo" TEXT,
  "isCritical" BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Menu Items
CREATE TABLE menu_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  section TEXT NOT NULL,
  name TEXT NOT NULL,
  "desc" TEXT NOT NULL,
  price NUMERIC NOT NULL,
  "foodCost" NUMERIC NOT NULL,
  hero BOOLEAN DEFAULT false,
  notes TEXT,
  "imageUrl" TEXT,
  ingredients JSONB DEFAULT '[]'::jsonb,
  "costPerBottle" NUMERIC,
  "sellPriceBottle" NUMERIC,
  "sellPriceGlass" NUMERIC,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Startup Costs
CREATE TABLE startup_costs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  budgeted NUMERIC NOT NULL,
  actual NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Operating Costs
CREATE TABLE operating_costs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category TEXT NOT NULL,
  monthly NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Milestones
CREATE TABLE milestones (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  milestone TEXT NOT NULL,
  date TEXT NOT NULL,
  phase TEXT NOT NULL,
  done BOOLEAN DEFAULT false,
  "assignedTo" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Notes
CREATE TABLE notes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tag TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  date TEXT NOT NULL,
  files JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Vendors
CREATE TABLE vendors (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  contact TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  category TEXT NOT NULL,
  "deliveryDays" JSONB DEFAULT '[]'::jsonb,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Inventory Items
CREATE TABLE inventory_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  department TEXT NOT NULL,
  "procurementStatus" TEXT NOT NULL,
  "vendorId" BIGINT REFERENCES vendors(id) ON DELETE SET NULL,
  price NUMERIC NOT NULL,
  "leadTime" TEXT NOT NULL,
  "currentStock" INT NOT NULL,
  "parLevel" INT NOT NULL,
  unit TEXT NOT NULL,
  "lastOrdered" TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Utility Accounts
CREATE TABLE utility_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  "accountNumber" TEXT NOT NULL,
  "loginInfo" TEXT NOT NULL,
  "monthlyCost" NUMERIC NOT NULL,
  "startDate" TEXT NOT NULL,
  "fileUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Permits
CREATE TABLE permits (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  issuer TEXT NOT NULL,
  "expiryDate" TEXT NOT NULL,
  status TEXT NOT NULL,
  "fileUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Marketing Posts
CREATE TABLE marketing_posts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  platform TEXT NOT NULL,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  status TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Training Modules
CREATE TABLE training_modules (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  completed BOOLEAN DEFAULT false,
  "videoUrl" TEXT,
  date TEXT,
  steps JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Daily Checklists
CREATE TABLE daily_checklists (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  shift TEXT NOT NULL,
  "assignedTo" TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Invoices
CREATE TABLE invoices (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "vendorName" TEXT NOT NULL,
  date TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  category TEXT NOT NULL,
  status TEXT NOT NULL,
  items JSONB DEFAULT '[]'::jsonb,
  "fileUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 15. Positions
CREATE TABLE positions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role TEXT NOT NULL,
  openings INT NOT NULL,
  hired INT NOT NULL,
  status TEXT NOT NULL,
  salary TEXT,
  "compPlan" TEXT,
  "offerLetterUrl" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. Candidates
CREATE TABLE candidates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  "resumeUrl" TEXT,
  stage TEXT NOT NULL,
  date TEXT,
  feedback TEXT,
  "trialScores" JSONB,
  "partnerNotes" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 17. Activity Logs
CREATE TABLE activity_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user" TEXT NOT NULL,
  action TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 18. Digital Assets
CREATE TABLE digital_assets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  url TEXT NOT NULL,
  "loginInfo" TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 19. Shopping List Items
CREATE TABLE shopping_list_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  quantity NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  "totalCost" NUMERIC NOT NULL,
  items TEXT DEFAULT '[]',
  category TEXT NOT NULL,
  department TEXT NOT NULL,
  "purchaseType" TEXT,
  "vendorName" TEXT,
  "storeName" TEXT,
  "storeUrl" TEXT,
  "sourceKey" TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 20. Cost Calculator Overrides
CREATE TABLE cost_calculator_overrides (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "itemId" BIGINT NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  price NUMERIC NOT NULL,
  "targetFoodCost" NUMERIC NOT NULL,
  ingredients JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS and create public policies temporarily (For Prototype Read/Write purposes)
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON tasks FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON menu_items FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE startup_costs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON startup_costs FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE operating_costs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON operating_costs FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON milestones FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON notes FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON vendors FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON inventory_items FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE utility_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON utility_accounts FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE permits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON permits FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE marketing_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON marketing_posts FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE training_modules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON training_modules FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE daily_checklists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON daily_checklists FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON invoices FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE positions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON positions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON candidates FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON activity_logs FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE digital_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON digital_assets FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE shopping_list_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON shopping_list_items FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE cost_calculator_overrides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public full access" ON cost_calculator_overrides FOR ALL USING (true) WITH CHECK (true);
