import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { google } from "googleapis";
import cookieParser from "cookie-parser";
import session from "express-session";
import { Readable } from "stream";
import pg from "pg";
import { InsForgeClient } from "@insforge/sdk";
import { GoogleGenAI } from "@google/genai";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const { Pool } = pg;

const DB_WRITE_TABLES = new Set([
  "tasks", "menu_items", "startup_costs", "operating_costs", "milestones", "notes",
  "vendors", "inventory_items", "utility_accounts", "permits", "marketing_posts",
  "training_modules", "daily_checklists", "invoices", "positions", "candidates",
  "digital_assets", "activity_logs"
]);

const DB_CONNECTION =
  process.env.DATABASE_URL ||
  "postgresql://postgres:211919448a449a8c985b520fc3895aeb@arqsta8h.us-west.database.insforge.app:5432/insforge?sslmode=require";

const toDbValue = (value: unknown) => {
  if (value === undefined) return null;
  if (Array.isArray(value) || (value !== null && typeof value === "object")) {
    return JSON.stringify(value);
  }
  return value;
};

async function startServer() {
  const app = express();
  const PORT = 3000;
  const pool = new Pool({ connectionString: DB_CONNECTION });
  const geminiApiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || process.env.VITE_GEMINI_API_KEY || "";

  await pool.query(`
    CREATE TABLE IF NOT EXISTS app_access_users (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      user_id TEXT,
      email TEXT UNIQUE NOT NULL,
      name TEXT,
      role TEXT NOT NULL DEFAULT 'Manager',
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_login_at TIMESTAMPTZ,
      revoked_at TIMESTAMPTZ,
      revoked_by TEXT
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS app_settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await pool.query(
    `INSERT INTO app_settings (key, value) VALUES ('app_title', 'ไกลกังวล') ON CONFLICT (key) DO NOTHING`
  );

  app.use(express.json({ limit: '50mb' }));
  app.use(cookieParser());
  app.use(session({
    secret: process.env.SESSION_SECRET || "restaurant-planner-secret",
    resave: false,
    saveUninitialized: true,
    cookie: { 
      secure: true, 
      sameSite: 'none',
      maxAge: 24 * 60 * 60 * 1000 // 24 hours
    }
  }));

  // Google OAuth Setup
  const oauth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID,
    process.env.GOOGLE_CLIENT_SECRET,
    `${process.env.APP_URL || "http://localhost:3000"}/auth/google/callback`
  );

  // InsForge Setup
  const insforgeUrl = (process.env.VITE_INSFORGE_URL || "https://arqsta8h.us-west.insforge.app").replace(/\/$/, "");
  const insforgeKey = process.env.VITE_INSFORGE_KEY || "ik_d3902514ce290fc64bb4900a677890ce";
  const insforge = new InsForgeClient({
    baseUrl: insforgeUrl,
    anonKey: insforgeKey,
  });

  // API routes
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  app.get("/api/auth/google/url", (req, res) => {
    const url = oauth2Client.generateAuthUrl({
      access_type: "offline",
      scope: ["https://www.googleapis.com/auth/drive.file"],
      prompt: "consent"
    });
    res.json({ url });
  });

  app.get("/auth/google/callback", async (req, res) => {
    const { code } = req.query;
    try {
      const { tokens } = await oauth2Client.getToken(code as string);
      (req.session as any).tokens = tokens;
      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ type: 'GOOGLE_AUTH_SUCCESS' }, '*');
                window.close();
              } else {
                window.location.href = '/';
              }
            </script>
            <p>Authentication successful. This window should close automatically.</p>
          </body>
        </html>
      `);
    } catch (error) {
      console.error("Google Auth Error:", error);
      res.status(500).send("Authentication failed");
    }
  });

  app.get("/api/auth/google/status", (req, res) => {
    res.json({ connected: !!(req.session as any).tokens });
  });

  app.post("/api/drive/save", async (req, res) => {
    const tokens = (req.session as any).tokens;
    if (!tokens) {
      return res.status(401).json({ error: "Not connected to Google Drive" });
    }

    const { name, type, base64 } = req.body;
    if (!name || !type || !base64) {
      return res.status(400).json({ error: "Missing file data" });
    }

    try {
      oauth2Client.setCredentials(tokens);
      const drive = google.drive({ version: "v3", auth: oauth2Client });

      const buffer = Buffer.from(base64, 'base64');
      const response = await drive.files.create({
        requestBody: {
          name: name,
          mimeType: type,
        },
        media: {
          mimeType: type,
          body: Readable.from(buffer),
        },
      });

      res.json({ success: true, fileId: response.data.id });
    } catch (error) {
      console.error("Drive Save Error:", error);
      res.status(500).json({ error: "Failed to save to Drive" });
    }
  });

  app.post("/api/ai/chat", async (req, res) => {
    if (!geminiApiKey) {
      return res.status(500).json({ error: "AI service is not configured" });
    }

    const { message, systemInstruction } = req.body || {};
    if (!message || !systemInstruction) {
      return res.status(400).json({ error: "Missing message or system instruction" });
    }

    try {
      const ai = new GoogleGenAI({ apiKey: geminiApiKey });
      const result = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: String(message),
        config: {
          systemInstruction: String(systemInstruction),
        },
      });

      return res.json({ text: result.text || "" });
    } catch (error: any) {
      console.error("AI chat error:", error);
      return res.status(500).json({ error: error?.message || "AI request failed" });
    }
  });

  app.post("/api/ai/invoice", async (req, res) => {
    if (!geminiApiKey) {
      return res.status(500).json({ error: "AI service is not configured" });
    }

    const { base64Data, mimeType } = req.body || {};
    if (!base64Data || !mimeType) {
      return res.status(400).json({ error: "Missing invoice image data" });
    }

    try {
      const ai = new GoogleGenAI({ apiKey: geminiApiKey });
      const prompt = "Extract invoice details: Vendor Name, Date (YYYY-MM-DD), Total Amount, Category (Operations, Food, Beverage, Marketing, Utilities), and a list of items (name, quantity, price). Return as JSON.";

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: {
          parts: [
            { text: prompt },
            { inlineData: { data: String(base64Data), mimeType: String(mimeType) } },
          ],
        },
        config: {
          responseMimeType: "application/json",
        },
      });

      return res.json({ text: response.text || "{}" });
    } catch (error: any) {
      console.error("AI invoice error:", error);
      return res.status(500).json({ error: error?.message || "Invoice AI request failed" });
    }
  });

  app.post("/api/db/write", async (req, res) => {
    const { table, action, payload, id } = req.body || {};

    if (!DB_WRITE_TABLES.has(table)) {
      return res.status(400).json({ error: "Invalid table" });
    }

    if (!["insert", "update", "delete"].includes(action)) {
      return res.status(400).json({ error: "Invalid action" });
    }

    try {
      if (action === "insert") {
        const data = payload || {};
        const keys = Object.keys(data);
        if (!keys.length) return res.status(400).json({ error: "Missing payload" });

        const columns = keys.map((k) => `"${k}"`).join(", ");
        const placeholders = keys.map((_, i) => `$${i + 1}`).join(", ");
        const values = keys.map((k) => toDbValue(data[k]));

        const q = `INSERT INTO ${table} (${columns}) VALUES (${placeholders}) RETURNING *`;
        const result = await pool.query(q, values);
        return res.json({ ok: true, row: result.rows[0] });
      }

      if (action === "update") {
        if (id === undefined || id === null) return res.status(400).json({ error: "Missing id" });
        const data = payload || {};
        const keys = Object.keys(data);
        if (!keys.length) return res.status(400).json({ error: "Missing payload" });

        const setClause = keys.map((k, i) => `"${k}" = $${i + 1}`).join(", ");
        const values = keys.map((k) => toDbValue(data[k]));

        const q = `UPDATE ${table} SET ${setClause} WHERE id = $${keys.length + 1} RETURNING *`;
        const result = await pool.query(q, [...values, id]);
        return res.json({ ok: true, row: result.rows[0] || null });
      }

      if (id === undefined || id === null) return res.status(400).json({ error: "Missing id" });
      const q = `DELETE FROM ${table} WHERE id = $1`;
      await pool.query(q, [id]);
      return res.json({ ok: true });
    } catch (error: any) {
      console.error("DB Write Fallback Error:", error);
      return res.status(500).json({ error: error?.message || "DB write failed" });
    }
  });

  app.get("/api/access/check", async (req, res) => {
    const email = String(req.query.email || "").trim().toLowerCase();
    if (!email) return res.status(400).json({ error: "Missing email" });

    try {
      const result = await pool.query(
        `SELECT email, role, is_active FROM app_access_users WHERE lower(email) = $1 LIMIT 1`,
        [email]
      );

      if (!result.rows.length) {
        return res.json({ exists: false, isActive: true, role: "Manager" });
      }

      const row = result.rows[0];
      return res.json({
        exists: true,
        isActive: !!row.is_active,
        role: row.role || "Manager",
      });
    } catch (error: any) {
      console.error("Access check error:", error);
      return res.status(500).json({ error: error?.message || "Access check failed" });
    }
  });

  app.post("/api/access/upsert-login", async (req, res) => {
    const email = String(req.body?.email || "").trim().toLowerCase();
    const userId = String(req.body?.userId || "").trim() || null;
    const inputName = String(req.body?.name || "").trim() || null;
    const requestedRole = String(req.body?.role || "Manager").trim();
    const hasOwnerLevelAccess = email === "yanajaib@gmail.com" || requestedRole === "Owner";
    const role = hasOwnerLevelAccess ? "Owner" : "Manager";
    const name = email === "yanajaib@gmail.com" ? "Partner" : inputName;

    if (!email) return res.status(400).json({ error: "Missing email" });

    try {
      const existing = await pool.query(
        `SELECT role, is_active FROM app_access_users WHERE lower(email) = $1 LIMIT 1`,
        [email]
      );

      const effectiveRole = hasOwnerLevelAccess ? "Owner" : (existing.rows[0]?.role || role);

      const result = await pool.query(
        `
        INSERT INTO app_access_users (user_id, email, name, role, is_active, last_login_at)
        VALUES ($1, $2, $3, $4, true, NOW())
        ON CONFLICT (email)
        DO UPDATE SET
          user_id = COALESCE(EXCLUDED.user_id, app_access_users.user_id),
          name = COALESCE(EXCLUDED.name, app_access_users.name),
          role = EXCLUDED.role,
          last_login_at = NOW()
        RETURNING email, role, is_active
        `,
        [userId, email, name, effectiveRole]
      );

      const row = result.rows[0];
      return res.json({ ok: true, isActive: !!row.is_active, role: row.role || "Manager" });
    } catch (error: any) {
      console.error("Access upsert error:", error);
      return res.status(500).json({ error: error?.message || "Access upsert failed" });
    }
  });

  app.get("/api/access/users", async (_req, res) => {
    try {
      const result = await pool.query(
        `
        SELECT id, email, name, role, is_active, created_at, last_login_at, revoked_at, revoked_by
        FROM app_access_users
        ORDER BY role DESC, created_at ASC
        `
      );
      return res.json({ ok: true, users: result.rows });
    } catch (error: any) {
      console.error("Access list error:", error);
      return res.status(500).json({ error: error?.message || "Access list failed" });
    }
  });

  app.post("/api/access/revoke", async (req, res) => {
    const email = String(req.body?.email || "").trim().toLowerCase();
    const revokedBy = String(req.body?.revokedBy || "Owner").trim();
    if (!email) return res.status(400).json({ error: "Missing email" });

    try {
      await pool.query(
        `
        UPDATE app_access_users
        SET is_active = false, revoked_at = NOW(), revoked_by = $2
        WHERE lower(email) = $1
        `,
        [email, revokedBy]
      );
      return res.json({ ok: true });
    } catch (error: any) {
      console.error("Access revoke error:", error);
      return res.status(500).json({ error: error?.message || "Access revoke failed" });
    }
  });

  app.post("/api/access/restore", async (req, res) => {
    const email = String(req.body?.email || "").trim().toLowerCase();
    if (!email) return res.status(400).json({ error: "Missing email" });

    try {
      await pool.query(
        `
        UPDATE app_access_users
        SET is_active = true, revoked_at = NULL, revoked_by = NULL
        WHERE lower(email) = $1
        `,
        [email]
      );
      return res.json({ ok: true });
    } catch (error: any) {
      console.error("Access restore error:", error);
      return res.status(500).json({ error: error?.message || "Access restore failed" });
    }
  });

  app.get("/api/settings/title", async (_req, res) => {
    try {
      const result = await pool.query(`SELECT value FROM app_settings WHERE key = 'app_title' LIMIT 1`);
      return res.json({ ok: true, title: result.rows[0]?.value || "ไกลกังวล" });
    } catch (error: any) {
      console.error("Settings title get error:", error);
      return res.status(500).json({ error: error?.message || "Settings read failed" });
    }
  });

  app.post("/api/settings/title", async (req, res) => {
    const title = String(req.body?.title || "").trim();
    if (!title) return res.status(400).json({ error: "Missing title" });

    try {
      await pool.query(
        `
        INSERT INTO app_settings (key, value, updated_at)
        VALUES ('app_title', $1, NOW())
        ON CONFLICT (key)
        DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
        `,
        [title]
      );
      return res.json({ ok: true, title });
    } catch (error: any) {
      console.error("Settings title update error:", error);
      return res.status(500).json({ error: error?.message || "Settings update failed" });
    }
  });

  app.post("/api/auth/change-password", async (req, res) => {
    const email = String(req.body?.email || "").trim().toLowerCase();
    const oldPassword = String(req.body?.oldPassword || "");
    const newPassword = String(req.body?.newPassword || "");

    if (!email || !oldPassword || !newPassword) {
      return res.status(400).json({ error: "Missing required fields" });
    }

    if (newPassword.length < 8) {
      return res.status(400).json({ error: "Password must be at least 8 characters" });
    }

    try {
      // Verify current password by attempting sign-in with InsForge
      const signInRes = await insforge.auth.signInWithPassword({
        email,
        password: oldPassword,
      });

      if (signInRes.error) {
        return res.status(401).json({ error: "Current password is incorrect" });
      }

      // Note: Password update is handled client-side via InsForge SDK
      // This endpoint verifies the old password and logs the change
      return res.json({ ok: true, message: "Password verified. Please complete update on client." });
    } catch (error: any) {
      console.error("Password verification error:", error);
      return res.status(500).json({ error: error?.message || "Password verification failed" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
